### ISSUE TITLE
problem with getFuncsMaxed()

### ISSUE THREAD

**Issue by FabianRoger** [jebyrnes/multifunc#1]
it seems that `getFuncsMaxed()` names the variables specified by `prepend` in order of specification and hence wrong if the order of specification is not the same as the order of the variables in the data frame. 

As far as I can see, the problem comes from how `getFuncMaxed()`, which is called internally, names the columns: 

```
ret <- data.frame(cbind(adf[, which(names(adf) %in% prepend)], funcMaxed))
names(ret) <- c(prepend, "funcMaxed")
```

this looks like it pulls out the right columns but then names them with the specified order from the prepend argument and not (necessarily) with the correct column names 

sorry if I'm wrong, hope it helps

**Comment by jebyrnes** [comment]
Indeed, and as the ordering was the same in the data I used to make the package, I didn't need to worry about this.  OK - fixed  now

```
ret <- data.frame(cbind(adf[, which(names(adf) %in% prepend)], funcMaxed))
names(ret) <- c(names(adf)[which(names(adf) %in% prepend)], "funcMaxed")
```
