### ISSUE TITLE
install_github fails

### ISSUE THREAD

**Issue by FabianRoger** [jebyrnes/multifunc#10]
error message: `ERROR: dependency ‘vegetarian’ is not available for package ‘multifunc’`

installing `vegetarian` manually solves the problem but maybe we should look into it?

Fabian

**Comment by FabianRoger** [comment]
by the way, if you don't want to use `vegetarian` you could also use `vegan::renyi(..., hill = TRUE)`

It doesn't do bootstrapping but neither does `eff_div()`, or? And it can take a vector of q-values (if we want to implement function profiles)

**Comment by jslefche** [comment]
Seems like a DESCRIPTION or NAMESPACE issue

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net

________________________________

**Comment by jebyrnes** [comment]
Hrm. It’s in the NAMESPACE under imports as generated by devtools...  I feel like I’m missing something simple…

On Jun 13, 2018, at 7:07 AM, Jon Lefcheck <notifications@github.com<mailto:notifications@github.com>> wrote:

Seems like a DESCRIPTION or NAMESPACE issue

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net<http://www.jonlefcheck.net>

________________________________

**Comment by AnlanYu-hub** [comment]
But how to get the vegetarian pacakage,I can't find it on CRAN

**Comment by jebyrnes** [comment]
Weird. Looks like it was removed. You can get it at https://cran.r-project.org/src/contrib/Archive/vegetarian/

I'm hoping to update the package in the next two months which should fix this.
