### ISSUE TITLE
problem with getCoefTab()

### ISSUE THREAD

**Issue by lebedeviu** [jebyrnes/multifunc#11]
Hello! Can't seem to find what's the problem, the code results in error
`bdLinearSlopes = getCoefTab(funcMaxed ~ Diversity, data = bdThreshes, groupVar = c("thresholds","Treat"),
                            coefVar = "Diversity", family = quasipoisson(link = "identity"), control = list(maxit=800))`

> Error in list_to_dataframe(res, attr(.data, "split_labels"), .id, id_as_factor) : 
  Results must be all atomic, or all data frames

Only happens if groupVar is a vector

**Comment by syq91** [comment]
@lebedeviu hi，i met same problem when run this code, do you have any suggestions? thanks

**Comment by jebyrnes** [comment]
Should now be fixed with the new update to tidyverse. If not, hit me with a reproducible example and I'll take a look.
