### ISSUE TITLE
package installation fails bc of 'vegetrian'

### ISSUE THREAD

**Issue by FabianRoger** [jebyrnes/multifunc#12]
```
Installing package into ‘/Users/fabian/Library/R/4.0/library’
(as ‘lib’ is unspecified)
ERROR: dependency ‘vegetarian’ is not available for package ‘multifunc’
* removing ‘/Users/fabian/Library/R/4.0/library/multifunc’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/3d/1w3blksj36bdt4t8sgsc90m40000gn/T//RtmpD7Z6e7/file22f05dd12250/multifunc_0.8.0.tar.gz’ had non-zero exit status
```
and if we [check for the package](https://cran.r-project.org/web/packages/vegetarian/index.html) on CRAN it tells us that Package ‘vegetarian’ was removed from the CRAN repository.

cheers

Fabian

**Comment by Suo-Liu** [comment]
>packageurl<-"https://cran.r-project.org/src/contrib/Archive/vegetarian/vegetarian_1.2.tar.gz"
> install.packages(packageurl, repos=NULL, type="source")

**Comment by jebyrnes** [comment]
Trying to remedy this in the larger sense, but, for now

`remotes::install_github("cran/vegetarian")`

will get you there.

Hrm - if that package no longer is on CRAN, did vegan or another package eat up its functions?
