### ISSUE TITLE
depending on MASS and plyr

### ISSUE THREAD

**Issue by FabianRoger** [jebyrnes/multifunc#2]
Hej,

I just used the multifunc package again but since I used it last time, I've been starting to using dplyr a lot. As it turns out, multifunc loads both MASS and plyr, which both have functions that mess with dplyr, especially `select` (MASS) and `mutate` (dplyr). 

I know little about this but If I understand right what I read [here](http://r-pkgs.had.co.nz/namespace.html) it seems like _importing_ these packages instead of _depending_ on them would prevent them from being put in the search path, which seems like it would solve the problem.

Is that right / would that be possible?

best

Fabian

---

heres the package loading message that I get when loading multifunc after dplyr:

```
> library(multifunc)
Loading required package: plyr
---------------------------------------------------------------------------------------------------
You have loaded plyr after dplyr - this is likely to cause problems.
If you need functions from both plyr and dplyr, please load plyr first, then dplyr:
library(plyr); library(dplyr)
---------------------------------------------------------------------------------------------------

Attaching package: ‘plyr’

The following objects are masked from ‘package:dplyr’:

    arrange, count, desc, failwith, id, mutate, rename, summarise, summarize

Loading required package: car
Loading required package: MASS

Attaching package: ‘MASS’

The following object is masked from ‘package:dplyr’:

    select
```

**Comment by jebyrnes** [comment]
Fixed!
