### ISSUE TITLE
R report that  "cannot open file './FunctContrastData.txt': No such file or directory"

### ISSUE THREAD

**Issue by youxinchen** [jebyrnes/multifunc#3]
When we practice 'Comparison of Sites' in accordance with file "multifunc_biodepth.rmd" ,R report an error "cannot open file './FunctContrastData.txt': No such file or directory".

**Comment by jebyrnes** [comment]
This looks like a data loading issue, not a multifunc issue. If you want to confirm, paste in the code where you ran into the error.

**Comment by youxinchen** [comment]
`all_biodepth<-read.table("./FunctContrastData.txt",header=T)
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file './FunctContrastData.txt': No such file or directory`

**Comment by youxinchen** [comment]
After I paste the following code in Rstudio
`all_biodepth<-read.table("./FunctContrastData.txt",header=T)`
I receive the following error:
`Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file './FunctContrastData.txt': No such file or directory`

**Comment by jslefche** [comment]
I agree with Jarrett that it sounds like the current working directory does not contain a file named `FunctContrastData.txt`. If you type the function `getwd` in the console, does it return the directory where that file is located?

**Comment by youxinchen** [comment]
No, I didn't find the file named `FunctContrastData.txt` in the directory returned.

**Comment by jslefche** [comment]
You'll need to specify the correct directory where the file is located using `setwd` - good luck!

**Comment by youxinchen** [comment]
I have searched  my whole disk C, but I did not find the file named `FunctContrastData.txt` still. @jslefche

**Comment by jslefche** [comment]
Are you trying to load your own data or an example?

**Comment by jebyrnes** [comment]
OH WAIT! You're working through some of the code from the paper. You don't need to do that to load the biodepth data any more. `data(all_biodepth)` should suffice.

**Comment by youxinchen** [comment]
Firstly,thank you for your help. In fact, I have ran the code of 'Comparison of Sites' use the data(all_biodepth) without the code `all_biodepth<-read.table("./FunctContrastData.txt",header=T)`, but I'm not sure whether the raw data needs to be transformed, I get the result of `indexTable` that is tinily different from yours.
the result of my `indexTable` 
**"location" "Tmin" "Tmax" "Tmde" "Rmde.linear" "Pmde.linear" "Mmin" "Mmax" "Mmde" "nFunc"
"542" "Germany" 0.14 0.91 0.48 0.168293040552893 0.538537729769258 5.05614203454894 1.17354446577095 4.42946257197697 5
"1" "Portugal" 0.08 0.45 0.29 0.216668887378138 0.505560737215656 6.12457504591458 3.92684928295104 6.4524637567895 6
"2" "Sweden" NA 0.71 0.43 0.267672978155123 0.535345956310247 NA 2.17658742100512 4.77577490219681 6
"3" "Sheffield" 0.57 NA 0.76 0.191150767663725 0.573452302991176 4.25968309859155 NA 3.9375 4
**
Secondly, after I run the following code in Rstudio
`slopePlot<-ggplot(bdLinearSlopes, aes(x=thresholds, y=Estimate)) +
  geom_ribbon(...) +
   ...+
  stat_abline(intercept=0, slope=0, lwd=0.6, linetype=2) +
  ...)`
I receive the following error:
`Error: could not find function "stat_abline"`
Then I find that `ggplot2` has removed the function 'stat_abline', I have to use the function `geom_abline`, maybe you can fix this issue.

Finally,I Plot `bdCurvesAll` and `slopePlot` in a single figure by code
`grid.arrange(bdCurvesAll,+slopePlot) `
It plots alright but shows:
`Warning messages:
1: Removed 5035 rows containing non-finite values (stat_smooth). 
2: Removed 5035 rows containing missing values (geom_point). `

**Comment by jebyrnes** [comment]
1) How different is it? As long as you followed what we did after loading the data, you should be OK. Small differences may result due to changing packages, etc., but there should be no large discrepancies.

2) stat_abline is no longer in ggplot2. It's been changed to geom_abline.

3) Looks like there is a problem upstream in generating your plot. Look at each one individually. You've got a bug in there somewhere that is keeping you from plotting any of the data.
