### ISSUE TITLE
getIndices() prompt that warning messages after using the standardized data

### ISSUE THREAD

**Issue by youxinchen** [jebyrnes/multifunc#4]
I run the code `IDX <- getIndices(LinearSlopes, Thresh, funcMaxed ~ otu16s)
` with my data which have been standardized, then I receive the following Warning messages:
`Warning messages:
1: In max(threshdata[[divvar]], na.rm = T) :
  no non-missing arguments to max; returning -Inf
2: In min(threshdata[[divvar]], na.rm = T) :
  no non-missing arguments to min; returning Inf
3: In getIndices(LinearSlopes, Thresh, funcMaxed ~ CYA_R) :
  None of these coefficients are different from 0, hence indices have little meaning`
and the result of IDX:
```
Tmin Tmax Tmde Rmde.linear Pmde.linear Mmin Mmax Mmde nFunc
1   NA   NA   NA          NA          NA   NA   NA   NA     7
```
But I can plot the slope  and relevant curves at different thresholds.
Do you think that the standardized data is the reason of these error.
My partial standardized data:
```
        v1          v2        v3          v4          v5
1 0.4032176 0.168808504 0.2990654 0.004056795 0.218805375
2 0.5947587 0.246549262 0.5950156 0.206896552 0.180153574
3 0.6885561 0.150325242 0.6573209 0.117647059 0.202395895
4 0.3101285 0.115976519 0.1017653 0.028397566 0.046182812
5 0.2763331 0.004838966 0.0384216 0.237322515 0.003894714
          v6         v7    otu16s
1 0.06403499 0.06968898 0.4983165
2 0.22034913 0.54607867 0.3804714
3 0.18608181 0.80712151 0.5690236
4 0.06938170 0.03636893 0.1784512
5 0.03314241 0.03114860 0.8047138
```

**Comment by jebyrnes** [comment]
Huh. If you look at your thresdata, are there any NA values? Or parts of the data set full of them?

**Comment by jebyrnes** [comment]
Just checking back as I did not get any response from the above query.

**Comment by lebedeviu** [comment]
Hello! I havea similar problem with my data which have not been standardized, but there are no NA values anywhere 
mb you can advice smth..

`> indexTable = lapply(levels(bdLinearSlopes$Treat), function(x) { 
+ slopedata = subset(bdLinearSlopes, bdLinearSlopes$Treat == x) 
+ threshdata = s .... [TRUNCATED] 

> indexTable = ldply(indexTable) 

> indexTable 
Treat Tmin Tmax Tmde Rmde.linear Pmde.linear Mmin Mmax Mmde nFunc 
1 C NA NA NA NA NA NA NA NA 11 
2 F 0.11 0.16 0.15 0.06435803 -Inf NA NA NA 11 
Warning messages: 
1: Length of logical index must be 1 or 40, not 8 
2: In max(threshdata[[divvar]], na.rm = T) : 
no non-missing arguments to max; returning -Inf 
3: In min(threshdata[[divvar]], na.rm = T) : 
no non-missing arguments to min; returning Inf 
4: In getIndices(slopedata, threshdata, funcMaxed ~ Real_div) : 
None of these coefficients are different from 0, hence indices have little meaning 
5: In max(threshdata[[divvar]], na.rm = T) : 
no non-missing arguments to max; returning -Inf 
6: In min(threshdata[[divvar]], na.rm = T) : 
no non-missing arguments to min; returning Inf`

**Comment by jebyrnes** [comment]
OK, I've gone back and reworked the entire package with tidyverse packages instead of plyr. Please check and see if this works. If it does not, hit me with a reprex and I'll fix it.
