### ISSUE TITLE
family argument pass to geom_smooth, default divvar in getindicese()

### ISSUE THREAD

**Issue by Xeonilian** [jebyrnes/multifunc#5]
Hi jebyrnes,
Thank you for the pacakge. 
I found there are two points not complicated but bothered me for a while to figure out.
### 1
I am trying the example code and noticed that 
the way of passing argments of glm is changed in ggplot.
now it is 
```
stat_smooth(method="glm", method.args = list(family = quasipoisson(link = "identity")), colour="red", lwd=0.6)
```
### 2
in function getindices(), divvar's default value is Diversity.
```
getIndices(slopedata, threshdata, eqn, fun = glm, divvar = "Diversity",
groupVar = "thresholds", showNfunc = T)
```

For me, divvar is not Diversity, actually not about diversity at all. I know if I read the help carefullly, I would have changed it before I figure out by debugging.
Perhaps, it could be more clear if divvar = "Diversity" is in the example codes.

Cheers

**Comment by jebyrnes** [comment]
Yeah, I know, divvar isn't very good, particularly as folk are now using this for more than diversity. Live and learn how to write good code, I suppose. You can of course put anything in "Diversity" - even categorical columns.

I'll work on revising the vignette with the next release version (some new things are coming. Thanks for the feedback!
