### ISSUE TITLE
problems with function Anova

### ISSUE THREAD

**Issue by NaiaraLopez** [jebyrnes/multifunc#6]
Hi1 Thank you very much for your package. A few months ago I analyzed some data and all was perfect. Now I have re-taken it to include some new data and performing threshold approach, the program says that Anova function does not exist.

Can anyone please help me? Maybe I am doing something wrong but  few months ago the same script ran perfectly....

**Comment by jebyrnes** [comment]
is `car` installed?

**Comment by NaiaraLopez** [comment]
Thabk you cery much for your answer. It was not properly installed.  
Now it runs perfectly. And thank your for creating this fantastic  
package!
