### ISSUE TITLE
hardwired eg in eff_div

### ISSUE THREAD

**Issue by robertbagchi** [jebyrnes/multifunc#7]
seems like the duffy data set has got hardwired into this function - 
{
    sapply(1:nrow(df), function(x) {
        dat <- duffy %>% select(eval(duffyAllVars.std))
        vegetarian::d(dat[x, ], q = q)
    })
}
should replace "dat" with "df" and remove definition of dat altogether.

**Comment by jebyrnes** [comment]
Oops - hadn't pushed this fix.
