### ISSUE TITLE
error in install_github related to vegetarian package

### ISSUE THREAD

**Issue by FabianRoger** [jebyrnes/multifunc#8]
I downloaded the newest multifunc version to run the code and got the following error: 

     install_github("multifunc", "jebyrnes")
     * installing *source* package ‘multifunc’ ...
     ** R
     ** data
     *** moving datasets to lazyload DB
     ** preparing package for lazy loading
     Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
       there is no package called ‘vegetarian’
     ERROR: lazy loading failed for package ‘multifunc’

after installing `vegetarian` separately it works.

**Comment by jebyrnes** [comment]
Oops - forgot the import. Fixed.
